# Generated by Django 3.2.12 on 2022-02-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('role', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('League', models.CharField(blank=True, max_length=20)),
                ('coach_name', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(blank=True, max_length=255, upload_to='')),
                ('url', models.URLField(blank=True, max_length=255)),
                ('slug', models.SlugField(default=models.CharField(blank=True, max_length=100))),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, default='None')),
                ('salary', models.CharField(blank=True, default='None', max_length=20)),
                ('picture', models.ImageField(blank=True, default='https://icon-library.com/images/2018/2503231_sharks-player-profile-silhouette-hd-png-download.png', upload_to='')),
                ('url', models.URLField(blank=True, max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.positions')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.teams')),
            ],
        ),
    ]
