# Generated by Django 3.2.12 on 2022-02-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField(blank=True)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('salary', models.CharField(blank=True, max_length=20)),
                ('team', models.SlugField(blank=True, max_length=255)),
                ('picture', models.ImageField(blank=True, max_length=255, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('city', models.SlugField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField(blank=True)),
                ('League', models.CharField(blank=True, max_length=20)),
                ('coach_name', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(blank=True, max_length=255, upload_to='')),
            ],
        ),
    ]
