# Generated by Django 3.2.12 on 2022-02-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_players_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='slug',
            field=models.SlugField(default=models.CharField(blank=True, max_length=100)),
        ),
    ]
