# Generated by Django 3.2.12 on 2022-02-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_players_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
