# Generated by Django 3.2.12 on 2022-02-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_teams_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
